[package]
name = "rubyfmt-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
rubyfmt = { git = "https://github.com/fables-tales/rubyfmt", rev = "5290e84a5db5ad943d1322b138597cb50808d811", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
