[package]
name = "rubyfmt-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
rubyfmt = { git = "https://github.com/fables-tales/rubyfmt", rev = "01fc523f42163269708c2c087644d43873ca2462", default-features = false }

[profile.release]
opt-level = 'z'
lto = true
